CREATE TABLE [dbo].[AdHocPages]
(
	[Id]		SMALLINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Url]		NVARCHAR(200) NOT NULL,
	[UserId]	NVARCHAR(128) NOT NULL
	/*CONSTRAINT FK_ASPNETUSERS_ID FOREIGN KEY  (UserId) REFERENCES  [dbo].[AspNetUsers](Id)*/
)
